use ifx now rather than ifort

diff --git a/patwarp/compile_patwarp_linux b/patwarp/compile_patwarp_linux
--- a/patwarp/compile_patwarp_linux
+++ b/patwarp/compile_patwarp_linux
@@ -10,11 +10,11 @@ cd $WARP3D_HOME/patwarp
 #
 # Test compiler (no real point in proceeding without ifort)
 #
-hash ifort 2>&- || { echo >&2 "The Intel fortran compiler is required (ifort).  Aborting."; exit 1;}
+hash ifx 2>&- || { echo >&2 "The Intel fortran compiler is required (ifx).  Aborting."; exit 1;}
 #
 # Now proceed.
-echo "Compiling patwarp on Linux 64 ..."
-ifort -O2 -xAVX -static-intel -fixed -traceback -fpe0 patwarp.f \
+echo "Compiling patwarp on Linux ..."
+ifx -O2 -static-intel -fixed -traceback -fpe0 patwarp.f \
        -o $WARP3D_HOME/run_linux/patwarp.go
 #
 echo "Executable is in run_linux"
